
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9
  - pytorch=2.5.1
  - numpy
  - pandas
  - requests
  - pathlib
  - biopython=1.84
  - tqdm
  - matplotlib
  - plotly
  - python-box



